name: Step Control

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 성공 step
        run: echo "성공"

      - name: 실패 step
        run: exit 1

      - name: 실패 후 이 step은?
        run: echo "이건 실행될까?"

      - name: 항상 실행
        if: always()
        run: echo "always()는 항상 실행됨"